version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: rubenw0/inventory-backend:latest
    container_name: django-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: inventorydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"

volumes:
  mysql_data:
